stages:
    - build

variables:
    GIT_SUBMODULE_STRATEGY: normal

build-debian:
    image: registry.videolan.org:5000/vlc-debian-unstable:20181128113529
    stage: build
    tags:
        - debian
        - amd64
    script:
        - autoreconf -fisv
        - mkdir build
        - cd build
        - ../configure
        - make -j $(getconf _NPROCESSORS_ONLN)

build-macos:
    stage: build
    tags:
        - macos
    script:
        - autoreconf -fisv
        - mkdir build
        - cd build
        - ../configure
        - make -j $(getconf _NPROCESSORS_ONLN)

build-win64:
    image: registry.videolan.org:5000/vlc-debian-win64:20181107154313
    stage: build
    tags:
        - debian
        - amd64
        - win64
    script:
        - autoreconf -fisv
        - mkdir build
        - cd build
        - ../configure --host=x86_64-w64-mingw32
        - make -j $(getconf _NPROCESSORS_ONLN)

build-win32:
    image: registry.videolan.org:5000/vlc-debian-win32:20181107151708
    stage: build
    tags:
        - debian
        - amd64
        - win32
    script:
        - autoreconf -fisv
        - mkdir build
        - cd build
        - ../configure --host=i686-w64-mingw32
        - make -j $(getconf _NPROCESSORS_ONLN)
